### ISSUE TITLE
"About" button

### ISSUE THREAD

**Issue by MacarenaCarrizosa** [josephdburdick/dahlia#10]
The About button in the top left menu always remains grey even when we are not on it as opposed to the other ones that get dark when you are in that section and then transparent when you are not.
This is by no means a priority btw.

**Comment by josephdburdick** [comment]
Try to click away from this menu, you may have it set on an active state.

**Comment by josephdburdick** [comment]
Oh I see what you mean now. This will be addressed in the next deploy.
