### ISSUE TITLE
Change text in "Make It happen" Button and Call to Action Section.

### ISSUE THREAD

**Issue by MacarenaCarrizosa** [josephdburdick/dahlia#14]
Rename the "Making it Happen" Button from the homepage to "Take Action".
Also change the "Call to Action" Tab and header to "Take Action" as well. Also change text in this section to:

Join our efforts in making this film a reality by emailing us "Supporting Dahlia Movie." When our Seed & Spark Campaign is live, we will contact you detailing the amazing perks you can enjoy as a THANK YOU for your support.

Button: Support Dahlia Movie (This can link to the email form for now).

 If you feel there is something else you can help us with or want to give us feedback, don't hesitate to contact us (link to contact us page) and tell us what’s in your mind. For now, share the link and spread the love!

**Comment by josephdburdick** [comment]
Resolved.
