### ISSUE TITLE
Dahlia title

### ISSUE THREAD

**Issue by MacarenaCarrizosa** [josephdburdick/dahlia#16]
Can you use the Bebas Nueu Font for the landing page and the titles on the tabs? I'm emailing you the font files.

**Comment by josephdburdick** [comment]
> for the landing page

When you say landing page, do you mean just the title and subtitle of the very first section? What about the titles of the remaining sections of the site? Convert them over to the new font?

> titles on the tabs

Do you mean the links of the primary navigation?

**Comment by MacarenaCarrizosa** [comment]
Most importantly for the landing page but it would be nice for continuity to have it in the remainder of the sections. Just for the titles.
