### ISSUE TITLE
About Section copy change

### ISSUE THREAD

**Issue by josephdburdick** [josephdburdick/dahlia#17]
@MacarenaCarrizosa, don't you feel like this copy:

> We are filmmakers who believe in the power of entertainment in creating awareness and inspiring people throughout the whole world.

would be better worded as:

> We are filmmakers who believe that the power of entertainment can create awareness and inspire people throughout the world.

**Comment by MacarenaCarrizosa** [comment]
Agreed. Thanks!

**Comment by josephdburdick** [comment]
Resolved.
