### ISSUE TITLE
add link to the dahlia site from my webpage

### ISSUE THREAD

**Issue by MacarenaCarrizosa** [josephdburdick/dahlia#18]
Can you please add a link on my website that takes you to the Dahlia site? 

Thanks!!

**Comment by josephdburdick** [comment]
Next time please open this issue up on that repository since the change will occur there. :wink: https://github.com/josephdburdick/macarena

**Comment by MacarenaCarrizosa** [comment]
ok! I didn't know I was a collaborator there thanks!

Macarena Carrizosa

Audiovisual Productions

+1 917 355 7974

E-Mail: macacarrizosa@gmail.com

---

_Before printing, think about the environment_
