### ISSUE TITLE
PRIORITY contact form is not working. 

### ISSUE THREAD

**Issue by MacarenaCarrizosa** [josephdburdick/dahlia#20]
This is kinda urgent. The contact form doesn't work. I put my email and message in and it says this:
![screen shot 2015-10-14 at 11 44 06 am](https://cloud.githubusercontent.com/assets/14558412/10488960/1ce727ee-7269-11e5-8651-99bce2c924d5.png)
But I never get the confirmation email, so I checked the resend button but still nothing. I checked all the folders in my email including the spam section. 

Maybe we should have the email there just in case this happens again. Also the more steps they have to take to contact us the more probability they wont follow through. 

Thanks!!

**Comment by MacarenaCarrizosa** [comment]
Nevermind. I got the email. Let's go through this when we meet.

**Comment by josephdburdick** [comment]
Resolved.
