### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by josephdburdick** [josephdburdick/dahlia#21]
Hey @MacarenaCarrizosa ,
I think it would be a good idea for you to sign up for Google Analytics (under _your_ Google account) so you can see who is going to your site. I am assigning this to you now, don't close this ticket when you finish– when you get the GA-Analytics account number paste it here and assign this back to me. :metal:

**Comment by MacarenaCarrizosa** [comment]
My tracking ID: UA-55665812-2

Copy paste the code:

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-55665812-2', 'auto');
  ga('send', 'pageview');
</script>

ANOTHER OPTION:
PHP ImplementationOPTIONAL
Create a PHP file named "analyticstracking.php" with the code above and include it on each PHP template page. Then, add the following line to each template page immediately after the opening <body> tag:
<?php include_once("analyticstracking.php") ?>

There is also a Dynamic Content Implementation Option, let me know if you need any other info. Thanks! :metal:
