### ISSUE TITLE
Social Media Links

### ISSUE THREAD

**Issue by MacarenaCarrizosa** [josephdburdick/dahlia#4]
On the Landing Page the Facebook Recommend and Like buttons are sharing the Macarena Productions website rather than Dahlia. Change the link for both and add an Instagram link for https://instagram.com/dahliamovie/.
Thanks!

**Comment by josephdburdick** [comment]
I'll change this asap. @MacarenaCarrizosa how do you imagine the Instagram link being positioned?

**Comment by MacarenaCarrizosa** [comment]
Right besides the Facebook "share" icon. I don't really understand the difference between "Share" and "Recommend" also I don't think the number of people who share it or recommend it is changing.
