### ISSUE TITLE
Profile pics

### ISSUE THREAD

**Issue by MacarenaCarrizosa** [josephdburdick/dahlia#5]
So this is really not a priority so please address it last but I think that it would be nice if the profile pics were kind of the same size, right now I feel that Anies' picture is too big. I like the size of mine, and Michelle is an intermediate, can we make our heads look kind of the same size?

**Comment by josephdburdick** [comment]
Hey @MacarenaCarrizosa, all images are exactly the same size, her face just takes up more of her photo. Not really something I can change in code; I'll need a different pic because of the way hers is cropped I can't really even correct it in Photoshop.

**Comment by MacarenaCarrizosa** [comment]
Oh ok let's not close the issue yet then because I will forget to get the updated photos.
